version: "3"

services:
  go-api-server:
    container_name: go-api-server
    platform: linux/x86_64
    hostname: localhost
    ports:
      - "8080:8080"
    tty: true
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - ./api:/go/src/app
